pipeline {
  agent any

  tools {
    nodejs "nodejs"
  }

  stages {
    stage('Clone Repository') {
      steps{
        echo "Clone repostiroy"
        git branch: "dev-fe", url: "https://github.com/this-is-seoul-soul/frontend-pwa", credentialsId: 'github_token'
      }
    }

    stage('Build React') {
      steps {
        dir('this-is-seoul-soul') {
          sh 'npm i -g pnpm'
          sh 'rm -rf pnpm-lock.yml'
          sh 'pnpm install'
          sh 'pnpm build'
        }
      }
    }

    stage('Build image') { 
      steps { 
        script {
          dir('this-is-seoul-soul') {
            sh "pwd"
            sh 'cp /var/jenkins_home/util/client/.env ./this-is-seoul-soul'
            sh "docker build -t seoulsoul_front ."
          }
        }
      } 
    }

    stage('Docker run') {
      steps {
        echo "docker compose build"
        sh "docker rm -f front"
        sh "docker-compose -f ./this-is-seoul-soul/docker-compose.yml up -d"
      }
    }

    stage('Finish') {
      steps {
        sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
      }
    }
  }

}