pipeline {
  agent any

  stages {
    stage('Clone Repository') {
      steps{
        echo "Clone repostiroy"
        git branch: "dev-fe", url: "https://github.com/this-is-seoul-soul/frontend-pwa", credentialsId: 'github_token'
      }
    }
    stage('Building image') { 
     steps { 
      script {
        sh "pwd"
        sh 'cp /var/jenkins_home/util/client/.env ./this-is-seoul-soul/'
        sh "docker build -f ./this-is-seoul-soul/Dockerfile -t seoulsoul_front ."
       }
     } 
    }

    stage('Docker build') {
     steps {
      echo "docker compose build"
      sh "docker-compose -f ./this-is-seoul-soul/docker-compose.yml build --no-cache"
     }
     post {
      success {
       echo "Success to build"
      }
      failure {
       echo "Docker build failed. clear unused file"
       sh "docker system prune -f"
       error 'pipeline aborted'
     }
    }
   }

    stage('Docker run') {
     steps {
      echo "docker compose build"
      sh "docker stop front"
      sh "docker rm front"
      sh "docker-compose -f ./this-is-seoul-soul/docker-compose.yml up -d"
     }
     post {
      success {
       echo "Success to run"
      }
      failure {
       echo "Docker run failed. clear unused file"
       error 'pipeline aborted'
     }
    }
   }

  }
}